### ISSUE TITLE
Can't decrypt with KDF enabled 

### ISSUE THREAD

**Issue by ViZiD** [wiktor-k/age-plugin-openpgp-card#3]
Hi, thx for nice plugin 
As soon as I enable KDF for pin, (r)age just doesn't want to accept my pin anymore.
I don't know if this is specifically related to your plugin, or if it's a (r)age issue, or a bug in my smart card firmware...
```bash
oct admin -c <card ident> generate --userid "Test Test <test@test.org>" --output pubkey.pub curve25519
age-plugin-openpgp-card | tee identity.txt
echo "TEXT TEXT TEXT" | rage -r age1xfz550f26tdnu2vf26kkxl8zn0cr8l3x0ctu2gstfgh8ga3n2aaq0j7fp6 -a > encrypted.age
# try decrypt without kdf
rage -d -i identity.txt < encrypted.age
TEXT TEXT TEXT
# enable kdf
oct system kdf-setup -c <card ident> 
# try decrypt again...
rage -d -i identity.txt < encrypted.age
# and... fail
Error: (stanza 0 0) OpenPGP card error status: Password not checked, 2 allowed retries

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]
```
I'm using [pico-openpgp](https://github.com/polhenarejos/pico-openpgp), it follows OpenPGP 3.4.1 specifications

In openpgp-card-tools/gpg2 sign and decrypt with KDF enabled works fine.

**Comment by wiktor-k** [comment]
Ha, good point. I'll circle back and discuss the KDF support with @hko-s (who's a developer behind the OpenPGP Card library I'm using) and get back to you.

Thanks for your kind words! :bow:

**Comment by wiktor-k** [comment]
Okay, folks. I've discussed the matter with @hko-s who said that mere update of his dependencies should resolve the KDF issue.

I've did so in https://github.com/wiktor-k/age-plugin-openpgp-card/pull/4 and also added KDF tests and it *seems* to be working. Would it be possible for you to test if that PR solves your issue?

If it's difficult I can release the new version anyway but it'd be good to know if that exact fix works for you.

See you later! :wave:

**Comment by hko-s** [comment]
The PR looks good to me, I think that should resolve the KDF issue :+1:

**Comment by ViZiD** [comment]
> good to know if that exact fix works for you
 I tested this pr and these changes solved the kdf issue
thx ❤️❤️❤️

**Comment by wiktor-k** [comment]
Okay, this should be available on crates.io too as version `0.1.1`.

Once again - thanks for reporting and have a nice day! :wave:
